apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: kurtev95/final-project:2.3
          ports:
            - containerPort: 8081
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                   name: postgres-secret
                   key: postgres-user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                   name: postgres-secret
                   key: postgres-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                   name: postgres-config
                   key: postgres-url
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
