version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: my-jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube:8.5.1-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - ~/sonarqube_conf:/opt/sonarqube/conf
      - ~/sonarqube_data:/opt/sonarqube/data
      - ~/sonarqube_extensions:/opt/sonarqube/extensions
      - ~/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db-sonar:
    image: postgres:13.1
    container_name: db-sonar
    hostname: db-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ~/sonar_db:/var/lib/postgresql
      - ~/sonar_data:/var/lib/postgresql/data


volumes:
  jenkins_home:
    external: true

