apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: NodePort
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30100